name: Dev Reusable workflow 

on:
  workflow_call:
    inputs:
      config-path:
        required: false
        type: string
    secrets:
      token:
        required: false

jobs:
  Explore-GitHub-Actions-Reusable-workflow:
    runs-on: ubuntu-latest
    
    steps:
      - name: test 
        shell: bash 
        run: echo "Dev"
