name: Dev Reusable workflow 

on:
  workflow_call:
    inputs:
      var1:
        required: true
        type: string
        default: "test"
    
jobs:
  called-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v3

      - name: Print the environment variables
        run: |
          echo ${{ inputs.var1 }}
          echo ${{ inputs.DAY_OF_WEEK }}
