name: Feature Reusable workflow 

on:
  workflow_call:
    inputs:
      var1:
        required: true
        type: string
        default: "test"
    
jobs:
  called-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Print the environment variables
        run: |
          echo ${{ inputs.var1 }}
          
