name: GH Reusable workflow 

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Branch
        options: 
        - master
        - dev
        - feature
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: test 
        if: github.ref == 'refs/heads/master'
        uses: selvan123/HelloWorld/blob/master/.github/workflows/dev.yml@master    
  
