name: GH Reusable workflow 

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: environment
        options: 
        - Dev
        - QA
        - Stage
jobs:
  
    GH-Dev:  
        if: github.ref == 'refs/heads/dev'
        uses: selvan123/HelloWorld/.github/workflows/dev.yml@feature   
        #uses: ./.github/workflows/dev.yml
        with:
          var1 : ${{ github.event.inputs.environment }}
  
    GH-Feature:  
        if: github.ref == 'refs/heads/feature'
        #uses: selvan123/HelloWorld/.github/workflows/feature.yml@feature 
        uses: ./.github/workflows/feature.yml
        with:
          var1 : ${{ github.event.inputs.environment }}
    
    
