# name: GH Reusable workflow 

# on:
#   workflow_dispatch:
#     inputs:
#       name:
#         type: choice
#         description: Env.
#         options: 
#         - master
#         - dev
#         - feature
# jobs:
#   Explore-GitHub-Actions:
##       if: github.ref == 'refs/heads/dev'
#       uses: selvan123/HelloWorld/.github/workflows/dev.yml@master    
  
name: Parent Workflow

on: 
   workflow_dispatch:
    inputs:
      environment:
        description: 'Enter Value'
        required: true
        default: 'staging'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: call repository dispatch workflow 
      run: |
        curl -H "Authorization: Bearer ${{ secrets.GHToken }}" -H 'Accept: application/vnd.github.everest-preview+json' "https://api.github.com/repos/selvan123/GH_Metrics/dispatches" -d '{"event_type": "awesomeness", "client_payload": {\"foo\": \"${{ secrets.GHToken }}\""}}'
