name: GH Reusable workflow 

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Branch
        options: 
        - master
        - dev
        - feature
jobs:
  Explore-GitHub-Actions:
      uses: selvan123/HelloWorld/.github/workflows/dev.yml@master    
  
