name: GH Reusable workflow 

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: samplevar
        options: 
        - Dev
        - QA
        - Stage
jobs:
  sample-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Print the environment variables
        run: |
          echo "hello"
          echo ${{ github.event.inputs.samplevar }}
  GH-Dev:  
        if: github.ref == 'refs/heads/dev'
        #uses: selvan123/HelloWorld/.github/workflows/dev.yml@feature   
        uses: ./.github/workflows/dev.yml
        with:
          var1 : ${{ github.event.inputs.samplevar }}
  
  GH-Feature:  
        if: github.ref == 'refs/heads/feature'
        #uses: selvan123/HelloWorld/.github/workflows/feature.yml@feature 
        uses: ./.github/workflows/feature.yml
        with:
          var1 : ${{ github.event.inputs.samplevar }}
    
    
