name: GH Reusable workflow 

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: env.
        options: 
        - Dev
        - QA
        - Stage
jobs:
  if: github.ref == 'refs/heads/feature'
  Explore-GitHub-Actions:  
  uses: selvan123/HelloWorld/.github/workflows/feature.yml@master    

  
