name: GH Reusable workflow 

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: env.
        options: 
        - Dev
        - QA
        - Stage
jobs:

  GH-Dev:  
      if: github.ref == 'refs/heads/dev'
      uses: selvan123/HelloWorld/.github/workflows/dev.yml@master    

  GH-Feature:  
      if: github.ref == 'refs/heads/feature'
      uses: selvan123/HelloWorld/.github/workflows/feature.yml@master    

  
  
